CREATE TABLE CRICKET(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT,
)
INSERT INTO CRICKET(NAME, CITY, AGE) 
VALUES
('Sachin Tendulkar' ,'Mumbai', 30),
('Rahul Dravid', 'BOMBAY' , 35),
('M. S. Dhoni' , 'Jharkhand', 31),
('Suresh Raina', 'Gujarat' , 30)
SELECT * INTO WORLDCUP FROM CRICKET
SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 0=1
SELECT NAME, CITY, AGE INTO IPL FROM CRICKET WHERE 0=1