--1
SELECT * FROM DEPOSIT
--2
SELECT * FROM BORROW
--3
SELECT * FROM BORROW
--4
SELECT ACTNO,CNAME,AMOUNT FROM Deposit
--5
SELECT LOANNO, Amount from BORROW
--6
SELECT * FROM BORROW WHERE BNAME='ANDHERI'
--7
SELECT ACTNO, AMOUNT FROM Deposit WHERE ACTNO=106
--8
SELECT BNAME FROM BORROW WHERE AMOUNT > 5000
--9
SELECT BNAME FROM Deposit WHERE ADATE > '1996-12-1'
--10
SELECT CNAME FROM Deposit WHERE ACTNO < 105
--11
SELECT BNAME FROM CUSTOMERS WHERE CITY = 'NAGPUR' OR CITY='DELHI'
--12
SELECT CNAME,BNAME FROM DEPOSIT WHERE AMOUNT > 4000 AND ACTNO <105
--13
SELECT CNAME FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000
--14
SELECT * FROM BORROW WHERE BNAME!='ANDHERI' --'!=' = '<>'
--15
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME='AJNI' OR BNAME='KAROLBAGH' OR BNAME='M.G.ROAD' AND ACTNO<104
--2.1
SELECT TOP 5 * FROM DEPOSIT
--2.2
SELECT TOP 3 * FROM DEPOSIT WHERE AMOUNT>1000
--2.3
SELECT TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME<>'ANDHERI'
--2.4
SELECT DISTINCT CITY FROM CUSTOMERS
--2.5
SELECT DISTINCT BNAME FROM BRANCH
--3.1
SELECT TOP 50 PERCENT * FROM BORROW
--3.2
SELECT TOP 10 PERCENT AMOUNT FROM DEPOSIT
--3.3
SELECT TOP 25 PERCENT CNAME FROM DEPOSIT WHERE AMOUNT>5000
--3.4
SELECT TOP 10 PERCENT AMOUNT FROM BORROW
--3.5
SELECT DISTINCT CITY FROM CUSTOMERS
--3.6
SELECT *,AMOUNT*(1.1) AS 'EXTRA AMOUNT' FROM BORROW -- AS '' OR []
--3.7
SELECT LOANNO FROM BORROW